### PR TITLE
feat: add mojavesoft license

### PR DESCRIPTION
**Pull request by jdev082**
pretty damn bad

### CODE REVIEW

**Comment by PPPDUD** [comment]
Please don't add this. It will only make me more popular, anyways.

**Comment by jdev082** [comment]
> Please don't add this. It will only make me more popular, anyways.

Undo all your mistakes then I guess...?

**Comment by PPPDUD** [comment]
What mistakes? It was all intentional.

**Comment by ErikMcClure** [comment]
Can't find the source for this, doesn't seem like an open-source license regardless.

**Comment by PPPDUD** [comment]
> Can't find the source for this, doesn't seem like an open-source license regardless.

Thank you for rejecting the license addition.

**Pull request closed without merging**
